name: Markdown Linter

on: [push, pull_request]

jobs:
  markdown-lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v2.0.0
        with:
          files: Document
          config_file: ".markdownlint.json"
          ignore_files: "Tools, node_modules, Crackmes, Samples"
