name: Spell Checker

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: "ba,bund,compliancy,firt,ist,keypair,ligh,ro,ser,synopsys,theses,zuser"
          skip: "*.json,*.yml,*.apk,*.ipa"
